#!/usr/bin/env python

from sys import argv
import os.path
import subprocess
import click

from q2d2 import markdown_templates, create_input_files

@click.group()
def cli():
    pass

def _prep_files(study_name, output_fn, remove_existing=False):
    os.makedirs(study_name, exist_ok=True)
    result = os.path.join(study_name, output_fn)

    if os.path.exists(result):
        if remove_existing:
            os.remove(result)
        else:
            print("%s has already been generated. Please remove or specify a "
                  "different analysis directory." % result)
            exit(1)
    return result

@cli.command('create-study')
@click.option('--study-name', "study_name",
              help="Descriptive name for your study.")
@click.option('--sample-metadata-filepath', "sample_metadata_filepath",
              help="Path to the sample metadata in tsv.")
@click.option('--otu-metadata-filepath', "otu_metadata_filepath",
              help="Path to the OTU metadata in tsv.")
@click.option('--unrarefied-biom-filepath', "unrarefied_biom_filepath",
              help="Path to the unrarefied BIOM table in classic (tsv) format.")
@click.option('--tree-filepath', "tree_filepath",
              help="Path to the phylogenetic tree in newick format.")
def create_study(study_name, sample_metadata_filepath,
                 otu_metadata_filepath, unrarefied_biom_filepath,
                 tree_filepath):

    os.makedirs(study_name, exist_ok=False)
    create_input_files(study_name,
                       sample_metadata=sample_metadata_filepath,
                       otu_metadata=otu_metadata_filepath,
                       unrarefied_biom=unrarefied_biom_filepath,
                       tree=tree_filepath)

    output_fn = _prep_files(study_name, '1.rarefy-biom.md')
    markdown_s = markdown_templates['rarefy-biom']()
    open(output_fn, 'w').write(markdown_s)

    output_fn = _prep_files(study_name, '1.biom-to-taxa-plots.md')
    markdown_s = markdown_templates['biom-to-taxa-plots']()
    open(output_fn, 'w').write(markdown_s)

    output_fn = _prep_files(study_name, '2.biom-to-pcoa.md')
    markdown_s = markdown_templates['biom-to-pcoa']()
    open(output_fn, 'w').write(markdown_s)

    output_fn = _prep_files(study_name, '2.biom-to-adiv.md')
    markdown_s = markdown_templates['biom-to-adiv']()
    open(output_fn, 'w').write(markdown_s)

    markdown_s = markdown_templates['index'](study_name, " ".join(argv))
    output_fn = _prep_files(study_name, 'index.md', remove_existing=True)
    open(output_fn, 'w').write(markdown_s)
    command = ' '.join(['ipython', 'notebook', os.path.join(study_name, 'index.md')])
    print("", "Run the following to start the Jupyter analysis environment:", command, "", sep='\n')

if __name__ == "__main__":
    cli()
